[phases.setup]
nixPkgs = ['go', 'nodejs', 'yarn', 'gcc']

[phases.install]
cmds = [
  'cd frontend && npm install',
  'cd backend && go mod download'
]

[phases.build]
cmds = [
  'cd frontend && npm run build',
  'cd backend && go build -o app main.go'
]

[start]
cmd = 'cd backend && ./app'

[variables]
STATIC_DIR = '/frontend/dist'